Feature/add zone transfer request
gophercloud/gophercloud pull request #2041
Opened 2020-10-17 14:01 UTC by GlaciErrDev

For #2040

https://github.com/openstack/designate/blob/056ceb7f4ba4a4b86fe212aa31a7506ac1b27f20/designate/api/v2/controllers/zones/tasks/transfer_accepts.py
https://github.com/openstack/designate/blob/056ceb7f4b/designate/api/v2/controllers/zones/tasks/transfer_requests.py

CRUD operations for `Zone Transfer Request` and `Zone Transfer Accept`

2020-10-25 20:24 UTC, jtopjian commented
@GlaciErrDev Thank you for submitting this. Is this ready for a review or are you still working on it?

At first glance, it looks like we might need some additional code references. For example, where are the fields in the `TransferAccept` struct defined (how do we know that `zone_transfer_request_id` is a valid field?), and how do we know that `target_project_id` is a valid field of the Transfer Request `CreateOpts`?

Once we're able to fully confirm the fields used in the request and result structs, a review of this PR should be fairly easy. 

Thanks again for your work and let me know if you have any questions.

2020-11-02 15:16 UTC, GlaciErrDev commented
@jtopjian Thank you for your review and comments.

Yes, it is a completely working API layer. Tested it on the deployed setup.

Left here some additional reference links ->

API Zone Transfer Request:
https://docs.openstack.org/api-ref/dns/#zone-ownership-transfers-requests

Reference to `target_project_id` field -> https://github.com/openstack/designate/blob/056ceb7f4b/designate/objects/adapters/api_v2/zone_transfer_request.py#L37 

API Zone Transfer Accept:
https://docs.openstack.org/api-ref/dns/#zone-ownership-transfers-accepts

Reference to `zone_transfer_request_id` field -> https://github.com/openstack/designate/blob/056ceb7f4b/designate/objects/adapters/api_v2/zone_transfer_accept.py#L26

If these will need to be added to the Issue description, just mention it :)

2020-11-03 21:41 UTC, jtopjian requested changes
@GlaciErrDev Thanks for the additional information.

I've made some comments for your review. The majority of them are just spacing issues related to the godoc code. They're nits, but semi-important as they get rendered as formatted code on godoc.org.

The other comment is about the `version` field.

One thing to note is that the DNS acceptance tests don't run by default on here. However, I've run them in a devstack environment and, short of the missing `version` field, everything else looks good.

Please let me know if you have any questions.

2020-11-04 15:43 UTC, GlaciErrDev commented on openstack/dns/v2/transfer/request/results.go
> +	Version int `json:"version"`
@jtopjian Thanks for the comments!

Seems that `version` leaves only in the API documentation and not in actual code... 
https://docs.openstack.org/api-ref/dns/?expanded=list-zone-transfer-requests-detail,create-zone-transfer-request-detail#id54
https://github.com/openstack/designate/blob/056ceb7f4ba4a4b86fe212aa31a7506ac1b27f20/api-ref/source/parameters.yaml#L672

So I will remove it from fields and from fixtures.

2020-11-04 15:43 UTC, GlaciErrDev commented
@jtopjian Thanks for the comments!

Seems that version leaves only in the API documentation and not in actual code...
https://docs.openstack.org/api-ref/dns/?expanded=list-zone-transfer-requests-detail,create-zone-transfer-request-detail#id54
https://github.com/openstack/designate/blob/056ceb7f4ba4a4b86fe212aa31a7506ac1b27f20/api-ref/source/parameters.yaml#L672

So I will remove it from fields and from fixtures.

2020-11-06 08:41 UTC, GlaciErrDev commented on openstack/dns/v2/transfer/request/doc.go
> +        targetProjectID := "f977bd7c-6485-4385-b04f-b5af0d186fcc"
It's strange, but the spacing is ok in the raw file. Maybe some issues with rendering in the diff?

2020-11-06 08:43 UTC, GlaciErrDev commented
@jtopjian I left a comment about spacing issues.

In the raw files, spacing is Ok. Maybe there is some strange rendering behavior in diffs?

2020-11-06 08:51 UTC, GlaciErrDev commented on openstack/dns/v2/transfer/request/doc.go
> +        targetProjectID := "f977bd7c-6485-4385-b04f-b5af0d186fcc"
It's strange, but the spacing is ok in the raw file. Maybe some issues with rendering in the diff?

2020-11-06 08:51 UTC, GlaciErrDev commented on openstack/dns/v2/transfer/request/doc.go
> +                TargetProjectID: targetProjectID,
It's strange, but the spacing is ok in the raw file. Maybe some issues with rendering in the diff?

2020-11-06 08:51 UTC, GlaciErrDev commented on openstack/dns/v2/transfer/accept/doc.go
> +        // Optionaly you can provide Status as query parameter for filtering the result.
It's strange, but the spacing is ok in the raw file. Maybe some issues with rendering in the diff?

2020-11-06 08:51 UTC, GlaciErrDev commented on openstack/dns/v2/transfer/accept/doc.go
> +        key := "JKHGD2F7"
It's strange, but the spacing is ok in the raw file. Maybe some issues with rendering in the diff?

2020-11-06 08:51 UTC, GlaciErrDev commented on openstack/dns/v2/transfer/accept/doc.go
> +		Key: key,
It's strange, but the spacing is ok in the raw file. Maybe some issues with rendering in the diff?

2020-11-06 08:51 UTC, GlaciErrDev commented on openstack/dns/v2/transfer/request/results.go
> +	Version int `json:"version"`
Removed it with new commit

2020-11-06 15:52 UTC, jtopjian commented
@GlaciErrDev Please see the attached image. This is what I see when I open the file in `vim`. There's a mix of tabs and spaces which are causing the misalignment.

Normally `go fmt` would resolve this, but since these blocks of code are embedded in comments, `go fmt` ignores them. If you normalize the file to either use tabs or spaces for the code blocks, it should all be good after that.

You should also be able to see the misalignment if you run:

```shell
$ go doc openstack/dns/v2/transfer/accept
```

![Screen Shot 2020-11-06 at 8 47 48 AM](https://user-images.githubusercontent.com/46959/98385913-cc0c8100-200c-11eb-81e2-c0e37de2b0f8.png)

2020-11-10 05:09 UTC, jtopjian approved these changes
LGTM - thank you!

There's still one small spacing issue, but I'll fix it post-commit :)

Thank you for your work and for contributing this.

2020-11-10 05:09 UTC, merged