[WIP] FWaaSv2.0 Policy CRUD
gophercloud/gophercloud pull request #2057
Opened 2020-11-13 15:40 UTC by codemanufaktur

follow up PR for  #1789 by @Elethiomel (I asked for the permission to get this done)
contains 2 cherry-picks from https://github.com/Daimler/gophercloud/commits/fwaas-v2 by @chrischdi 

For #514

https://github.com/openstack/neutron-lib/blob/56033ba643812a30577f6ab17648806c2ee494ba/neutron_lib/api/definitions/firewall_v2.py#L159
https://github.com/openstack/neutron-fwaas/blob/27906d0acff349c9e5ac7955d203fb2233c295db/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L148

<sub>Georg Schreiber georg.g.schreiber@daimler.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

2020-11-16 15:54 UTC, codemanufaktur commented
here is the output of [acceptance/openstack/networking/v2/extensions/fwaas_v2/policy_test.go](https://gist.github.com/codemanufaktur/13698e5a2a13d0430defa2f3d8e91a27)

2020-11-30 15:53 UTC, codemanufaktur commented
@Elethiomel @jtopjian ptal :-)

2020-12-02 20:49 UTC, jtopjian requested changes
@codemanufaktur Thank you for working on this and for the test output 🙂 

I've left a few comments - mostly just renaming fields. Please let me know if you have any questions.

2020-12-08 09:58 UTC, chrischdi commented on openstack/networking/v2/extensions/fwaas_v2/rules/results.go
> +	FirewallPolicyID     []string `json:"firewall_policy_id"`
Hi @jtopjian , if I did see it right, then `firewall_policy_id` was introduced as array:
See commit: https://github.com/openstack/neutron-fwaas/commit/55fed400b0511132b352b9a1fa0d2f55fc1bcbb8

Also here the reference to the neutron-fwaas codebase: https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L282

2020-12-08 14:28 UTC, codemanufaktur commented on openstack/networking/v2/extensions/fwaas_v2/policies/requests.go
> +type InsertRuleOpts struct {
good point, thx! I changed it as you suggested :-)

2020-12-09 03:01 UTC, jtopjian approved these changes
LGTM - thank you!

2020-12-09 03:01 UTC, merged