Octavia: Support listener tags
gophercloud/gophercloud pull request #2214
Opened 2021-09-11 12:09 UTC by lingxiankong

For: #2213

Octavia code: https://github.com/openstack/octavia/blob/69d975d62315624bf15c02f5dfefe30c013e63cf/octavia/api/v2/types/listener.py#L57

2021-09-11 23:13 UTC, lingxiankong commented
@jtopjian This PR is ready for review

2021-09-12 19:07 UTC, jtopjian requested changes
@lingxiankong Thanks! Just one small doc fix and this is good to go.

2021-09-12 19:07 UTC, jtopjian commented on openstack/loadbalancer/v2/listeners/doc.go
> +		Tags: []string{"prod"},
This should be a pointer.

```go
        i1001 := 1001
	i181000 := 181000
        tags := []string{"prod"}
	updateOpts := listeners.UpdateOpts{
		ConnLimit: &i1001,
		TimeoutClientData: &i181000,
		TimeoutMemberData: &i181000,
		Tags: &tags,
        }
```

2021-09-14 11:11 UTC, lingxiankong commented on openstack/loadbalancer/v2/listeners/doc.go
> +		Tags: []string{"prod"},
Done, thanks for review!

2021-09-14 13:28 UTC, jtopjian approved these changes
LGTM - Thanks!

2021-09-14 13:28 UTC, jtopjian commented
I think the OpenLab error is ignorable.

2021-09-14 13:28 UTC, merged

2021-09-14 20:57 UTC, lingxiankong commented
Thanks @jtopjian 

May I know when the next release is scheduled?

2021-09-14 22:37 UTC, jtopjian commented
@lingxiankong releases are generally ad-hoc. There aren't any other PRs in queue, so I've just created a v0.21.0 release.