Identity v3: OS-EP-FILTERS endpoint groups list/get
gophercloud/gophercloud pull request #2316
Opened 2022-01-10 11:35 UTC by garbage-collector

For #1889

API doc:
https://docs.openstack.org/api-ref/identity/v3-ext/index.html#os-ep-filter-api

API calls:
https://github.com/openstack/keystone/blob/ba2e4b83e88d5c1576e9d2cd6a760367deef3a62/keystone/api/os_ep_filter.py#L68-L79

Structures: https://github.com/openstack/keystone/blob/ba2e4b83e88d5c1576e9d2cd6a760367deef3a62/keystone/catalog/backends/sql.py#L605

EndpointGroupFilter structure: https://github.com/openstack/keystone/blob/ba2e4b83e88d5c1576e9d2cd6a760367deef3a62/keystone/api/os_ep_filter.py#L54

Note: this is a new proposal based on this PR: https://github.com/gophercloud/gophercloud/pull/1893 
I took care of the latests comments to move forward on this topic.
If there are better ways to do it, feel free to share it and close this PR. Thanks !

2022-02-03 20:24 UTC, EmilienM commented on acceptance/openstack/identity/v3/endpointgroups_test.go
> +	clients.SkipRelease(t, "stable/queens")
We don't support these releases in CI, you can remove these lines.

2022-02-03 20:26 UTC, EmilienM commented
LGTM, just curious about the decreased testing coverage reported by the bot. Can you explain it? Otherwise I think this is ready to go.

2022-05-21 19:32 UTC, mandre commented
Hi @garbage-collector,

> Note: this is a new proposal based on this PR: https://github.com/gophercloud/gophercloud/pull/1893
I took care of the latests comments to move forward on this topic.
If there are better ways to do it, feel free to share it and close this PR. Thanks !

Unfortunately github doesn't allow multiple people working on the same PR unless all contributors have write access to the repository. One way to do it would be to submit the PR from an organization fork, if you folks work for the same org. Another way would be to have @pgaxatte add you as a contributor to his repo. Have you tried contacting him? That's what I would do first, as he may still be interested to work on his PR.
Otherwise, opening a new PR is fine I guess, however it would be good to add @pgaxatte as a co-author if you're not cherry-picking his commits directly to give him credit for the initial work. Simply add a line with `Co-authored-by: name <name@example.com>` at the end of the commit message.

2023-08-25 07:26 UTC, pgaxatte commented
Hello,

I'd like to forfeit my changes to @garbage-collector. We actually work for the same team and he took over this work when I didn't need to move one further.

I will completely drop the PR on my side.

Do you need me to do more than that?

2023-08-25 08:41 UTC, pgaxatte commented
Hello,

I'd like to forfeit my changes to @garbage-collector. We actually work for the same team and he took over this work when I didn't need to move one further.

I completely dropped the PR on my side.

Do you need me to do more than that?

2023-08-25 14:45 UTC, EmilienM commented on acceptance/openstack/identity/v3/endpointgroups_test.go
> +	clients.SkipRelease(t, "stable/queens")
@garbage-collector please see that comment

2023-08-25 14:46 UTC, EmilienM requested changes
LGTM with a minor comment.

2023-11-23 22:41 UTC, closed without merging