add support restoring a soft-deleted server and tests
gophercloud/gophercloud pull request #2385
Opened 2022-04-22 23:30 UTC by Robin5911

Fixes https://github.com/gophercloud/gophercloud/issues/2368

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://docs.openstack.org/api-ref/compute/?expanded=restore-soft-deleted-instance-restore-action-detail

2022-04-25 15:33 UTC, EmilienM commented on openstack/compute/v2/servers/requests.go
> +// Restore  a soft-deleted server.
trailing space here

2022-04-25 15:33 UTC, EmilienM requested changes
Could you add acceptance test as well? If possible.
Thanks

2024-09-26 13:13 UTC, pierreprinetti commented on openstack/compute/v2/servers/requests.go
> +	resp, err := client.Post(actionURL(client, id), map[string]interface{}{"restore": ""}, nil, nil)
The docs say `"restore": null`. Am I missing something? Why is it `""` here?

2024-09-26 13:14 UTC, pierreprinetti commented on openstack/compute/v2/servers/requests.go
> +	resp, err := client.Post(actionURL(client, id), map[string]interface{}{"restore": ""}, nil, nil)
cf https://docs.openstack.org/api-ref/compute/?expanded=restore-soft-deleted-instance-restore-action-detail#restore-soft-deleted-instance-restore-action

2024-09-26 13:15 UTC, pierreprinetti commented
I am closing this PR as stale. @Robin5911 (or anyone else) please reopen if you are willing to bring this to completion

2024-09-26 13:15 UTC, closed without merging