Neutron v2: BGP Speaker Update and Add/Remove BGP Peer
gophercloud/gophercloud pull request #2400
Opened 2022-05-11 02:12 UTC by shhgs

Neutron V2: BGP Dynamic Routing
For #2208

```
$ git diff --stat HEAD^ 
 acceptance/openstack/networking/v2/extensions/bgp/peers/bgppeers_test.go       | 28 +++-------------------------
 acceptance/openstack/networking/v2/extensions/bgp/peers/peers.go               | 32 ++++++++++++++++++++++++++++++++
 acceptance/openstack/networking/v2/extensions/bgp/speakers/bgpspeakers_test.go | 89 +++++++++++++++++++++++++++++++++++++++++------------------------------------------------
 acceptance/openstack/networking/v2/extensions/bgp/speakers/speakers.go         | 38 ++++++++++++++++++++++++++++++++++++++
 openstack/networking/v2/extensions/bgp/speakers/doc.go                         | 42 ++++++++++++++++++++++++++++++++++++++++--
 openstack/networking/v2/extensions/bgp/speakers/requests.go                    | 91 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---
 openstack/networking/v2/extensions/bgp/speakers/results.go                     | 41 +++++++++++++++++++++++++++++++++++++++++
 openstack/networking/v2/extensions/bgp/speakers/testing/fixture.go             | 33 +++++++++++++++++++++++++++++++++
 openstack/networking/v2/extensions/bgp/speakers/testing/requests_test.go       | 83 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 openstack/networking/v2/extensions/bgp/speakers/urls.go                        | 15 +++++++++++++++
 10 files changed, 414 insertions(+), 78 deletions(-)
```

2022-05-11 02:37 UTC, shhgs commented
The OpenStack API doc for [add_bgp_peer](https://docs.openstack.org/api-ref/network/v2/?expanded=update-a-bgp-speaker-detail,remove-bgp-peer-from-a-bgp-speaker-detail#add-bgp-peer-to-a-bgp-speaker) and [remove_bgp_peer](https://docs.openstack.org/api-ref/network/v2/?expanded=update-a-bgp-speaker-detail,remove-bgp-peer-from-a-bgp-speaker-detail#remove-bgp-peer-from-a-bgp-speaker) is wrong. I believe the correct URL can be found in the source code, check [L69](https://github.com/openstack/neutron-dynamic-routing/blob/master/neutron_dynamic_routing/policies/bgp_speaker.py#L69) and [L80](https://github.com/openstack/neutron-dynamic-routing/blob/master/neutron_dynamic_routing/policies/bgp_speaker.py#L80).

2022-05-11 02:39 UTC, shhgs commented
I finally decided to split the PR. There are still 3 methods that's not been done for bgp/speakers. And that shall come in the next PR. 

- `/v2.0/bgp-speakers/{bgp-speaker-id}/get_advertised_routes`
- `/v2.0/bgp-speakers/{bgp-speaker-id}/add_gateway_network`
- `/v2.0/bgp-speakers/{bgp-speaker-id}/remove_gateway_network`

2022-05-11 12:21 UTC, shhgs commented
```
        }
3372
    convenience.go:236: Failure in mtu_test.go, line 132:at .Network.UpdatedAt expected time.Date(2022, time.May, 11, 3, 58, 51, 0, time.UTC), but got time.Date(2022, time.May, 11, 3, 58, 52, 0, time.UTC)
3373
    convenience.go:35: Failure in mtu_test.go, line 132: The structures were different.
3374
    networking.go:479: Attempting to delete network: a034f49a-cf12-440e-89bd-b66fd71408a5
3375
    networking.go:486: Deleted network: a034f49a-cf12-440e-89bd-b66fd71408a5
```

2022-05-16 17:24 UTC, shhgs commented
Hi @mandre, 

I've updated the PR. 

1. Rename the xxxOptBuilder to xxxOptsBuilder
2. Using `UpdateOptsBuilder`, `AddBGPPeerOptsBuilder` and `RemoveBGPPeerOptsBuilder` instead of xxxOpts. 
3. move `AddBGPPeerOpts` to `requests.go` and also defined a `RemoveBGPPeerOpts`.

2022-05-20 12:45 UTC, mandre requested changes
Great, let's [restore the coverage for speakers.List()](https://github.com/gophercloud/gophercloud/pull/2400#discussion_r873184854) and we should be good to merge.

2022-05-20 13:14 UTC, shhgs commented
@mandre 

I forget to leave this test behind. I've added it back. Please check it out.

2022-05-20 15:06 UTC, mandre approved these changes
Sweet, thanks for the quick update @shhgs. I see ussuri fails to install devstack, this has nothing to do with your patch, and since the other jobs all came back green, we have enough signals that your PR is good. LGTM.

2022-05-20 15:06 UTC, merged