Introduce context usage in the service client
gophercloud/gophercloud pull request #2686
Opened 2023-07-11 05:36 UTC by pkenchap

Context usage in the gopher cloud gives more request handling and goroutines working on a request typically needs access to request-specific values such as the identity of the end user, authorization tokens, and the request’s deadline. if we enable the context which provide easy integration external tools .

why we are proposing to have a context in the client is to integration of **Opentelemetry (**https://github.com/open-telemetry/opentelemetry-go) in the Gophercloud sdk (https://github.com/gophercloud/gophercloud) . provides the tracing of the API can be monitored with the timelines, which gives immense use for the performance test for calculation individual api time taken for the operation. Also gives a nice UI based graphs using the JaegerUI .
Prior to starting a PR, please make sure you have read our
[contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

we may need to pass the context parameter to functions in the service_client.go file .
For example : Adding the ctx context.Context to the function which has these REST API endpoints .
func (client *ServiceClient) Get(ctx context.Context, url string, JSONResponse interface{}, opts *RequestOpts) (*http.Response, error)

But service client will call the Request method in the Provider_client it does not contain to have a context , only when we call the do_request 
https://github.com/pkenchap/gophercloud/blob/cf659998b191737a8e9116dcf2f31918635558af/service_client.go#L153

if we use the https://github.com/pkenchap/gophercloud/blob/cf659998b191737a8e9116dcf2f31918635558af/provider_client.go#L363

do request method for the context in the service client then we can provide the context to the provider_client . 

https://github.com/gophercloud/gophercloud/issues/2670

Fixes #2670

2023-07-12 09:52 UTC, pierreprinetti reviewed
Thank you for submitting this. I think we can work towards a solution that fulfills both your needs and Gophercloud requirements. Below my observations.

### Backwards compatibility
To ensure backwards compatibility, please leave all function signatures as they are. Instead, move the current logic to functions named `XxxWithContext(ctx context.Context, ...` and have the old signatures be empty convenience functions that just call the Context ones with `context.Background()`.

Example:
```Go
// OLD FUNCTION
func Get(client *gophercloud.ServiceClient, id string) (r GetResult) {
	resp, err := client.Get(getURL(client, id), &r.Body, &gophercloud.RequestOpts{}
	// ...
}
```

should be replaced in your PR by:
```Go
func GetWithContext(ctx context.Context, client *gophercloud.ServiceClient, id string) (r GetResult) {
	resp, err := client.Get(getURL(client, id), &r.Body, &gophercloud.RequestOpts{}
	// ...
}

func Get(client *gophercloud.ServiceClient, id string) (r GetResult) {
	return GetWithContext(context.Background(), client, id)
}
```

### Context for cancellation
In your PR, the context injected in each call is consumed in `ServiceClient.{Get,Post,Put}` for tracing, and then stops there. From the caller's point of view, it is surprising that cancellation and values carried by the context don't continue their journey to `ServiceClient.Request` and eventually to the actual HTTP call within `ProviderClient`.

In other words: with your PR I can call `Get(ctx, ...)` with a cancelled context, and the call goes through.

If you decide to walk the walk and wire the context down to the ProviderClient `doRequest` method, beware that once there, you will find that [a context already exists](https://github.com/gophercloud/gophercloud/blob/cfd55f162d743c5e7eaefb8c24cf7b001108fe03/provider_client.go#L397-L399). I had drafted [a context-merging function](https://github.com/gophercloud/gophercloud/pull/2274/files#diff-552f47512a00afe5fc6850cc9ddc830a6daeca162750e50aab4ed549685e0253) in a previous experiment; if you have a better idea you are very welcome to bring it to the table.


### No opinionated tracing in Gophercloud
I don't think that Gophercloud should include tracing out-of-the-box. Or least, not in the main repo.
The good new is that once you bring your context to the ProviderClient, you can let your consumer application override the Transport in the ProviderClient's HTTPClient and wire your tracing from there.

An example (I have copy-pasted and adapted the call to the tracer you have in this PR):

```Go
type tracingTransport struct {
	transport http.RoundTripper
}

func (t *tracingTransport) RoundTrip(req *Request) (*http.Response, error) {
	_, span := trace.SpanFromContext(req.Context()).Tracer().Start(req.Context(), req.Method+" : "+req.URL.String())
	defer span.End()
	return t.transport(req)
}

func main() {
	opts := clientconfig.ClientOpts{Cloud: os.Getenv("OS_CLOUD")}

	client, err := clientconfig.NewServiceClient("compute", &opts)
	if err != nil {
		panic(err)
	}

	client.ProviderClient.HTTPClient.Transport = tracingTransport{client.ProviderClient.HTTPClient.Transport}

	// use the client ...
}
```
---

What do you think?

2023-07-12 09:52 UTC, pierreprinetti commented on service_client.go
> +	response, err := client.Request("GET", url, opts)
`ctx` should continue its journey down to the `ServiceProvider` through `client.Request`

2023-07-12 09:52 UTC, pierreprinetti commented on service_client.go
> +	response, err := client.Request("POST", url, opts)
`ctx` should continue its journey down to the `ServiceProvider` through `client.Request`

2023-07-12 14:11 UTC, pkenchap commented
@pierreprinetti , Thanks for your valuable inputs. 
I agree with your comment that we need to travers the context till the ProviderClient's doRequest function .
I will make sure how it behaves with the backward compatibility by using the `context.Background()` as shown in the comment with `xxwithcontext`. Actually I thought user will pass the context so it will travers from the `request.go` files to server_client. but from the example you gave looks for every call the tracing will get invoked where the `HTTP.client` is involved . Then in the PR's request.go files need no modification isn't it . 
I will try these in my test env and I'll share the insights of it .

2023-08-02 04:15 UTC, pkenchap commented
@pierreprinetti , Please take a look .

2023-08-07 08:29 UTC, pierreprinetti requested changes
This is a good start, however there's still a lot of work to do to add `WithContext` versions of each call. Maybe something that can be achieved with some scripting?

2023-08-07 08:29 UTC, pierreprinetti commented on openstack/ot/jaeger.go
> +package ot
Please delete this file. As mentioned in a previous comment (see "No opinionated tracing in Gophercloud"), tracing can be added right from the application; I see no need for it in the library.

2023-08-07 08:29 UTC, pierreprinetti commented on service_client.go
> +func (client *ServiceClient) Request(ctx context.Context, method, url string, options *RequestOpts) (*http.Response, error) {
This is an exported method: we can't change it without breaking compatibility. Please leave this function signature as-is, and add a `RequestWithContext` method like you did for the other ones in this same file.

2023-08-07 08:29 UTC, pierreprinetti commented on openstack/utils/choose_version.go
> +	_, err := client.Request(context.Background(), "GET", client.IdentityBase, &gophercloud.RequestOpts{
Please create a `ChooseVersionWithContext` that accepts a context instead, then add a `ChooseVersion` function for backwards compatibility

2023-08-07 08:29 UTC, pierreprinetti commented on openstack/cdn/v1/services/requests.go
> +	resp, err := c.Request(context.Background(), "PATCH", url, &gophercloud.RequestOpts{
To add cancellation capabilities to this `Update` function, create a `UpdateWithContext` clone and turn this into a convenience function that adds a `context.Background()`.

```Go
func Update(c *gophercloud.ServiceClient, idOrURL string, opts UpdateOpts) (r UpdateResult) {
	return UpdateWithContext(context.Background(), c, idOrURL, opts)
```

2023-08-23 21:36 UTC, pierreprinetti commented
Hey @pkenchap,
Are you willing to continue the work on this PR?

2023-08-24 05:50 UTC, pkenchap commented
> Hey @pkenchap,
> Are you willing to continue the work on this PR?

Yes , I am working on this PR.

2023-08-24 06:32 UTC, pkenchap commented
I had addressed the changes , please take a look .

2023-08-25 12:18 UTC, pierreprinetti commented on openstack/objectstorage/v1/swauth/requests.go
> +	resp, err := c.Request(context.Background(), "GET", getURL(c), &gophercloud.RequestOpts{
Please avoid generating "root" context objects outside convenience functions.

Here you could create `AuthWithContext` that accepts a context, then add a convenience function `Auth` for backwards compatibility that calls `AuthWithContext` with a `context.Background()`.

2023-08-30 08:05 UTC, pierreprinetti commented
@EmilienM Can you please have a look at go-apidiff? [It's reporting changes](https://github.com/gophercloud/gophercloud/actions/runs/6020851759/job/16332803566?pr=2686#step:5:191) in files this PR didn't touch. I suspect that it may be comparing this branch with the latest release, rather than its base commit.

2023-08-30 23:45 UTC, EmilienM commented
> @EmilienM Can you please have a look at go-apidiff? [It's reporting changes](https://github.com/gophercloud/gophercloud/actions/runs/6020851759/job/16332803566?pr=2686#step:5:191) in files this PR didn't touch. I suspect that it may be comparing this branch with the latest release, rather than its base commit.

https://github.com/gophercloud/gophercloud/pull/2740

2023-09-01 15:02 UTC, EmilienM commented
This PR should be rebased to get the latest github workflow changes, otherwise the go-apidiff will keep failing. I think this has been resolved by https://github.com/gophercloud/gophercloud/pull/2740 for future PRs.

2023-09-07 11:39 UTC, pierreprinetti commented on openstack/objectstorage/v1/swauth/requests.go
> +func AuthWithContext(c *gophercloud.ProviderClient, opts AuthOptsBuilder) (r GetAuthResult) {
Copy paste problem? This function doesn't accept a context

2023-09-07 11:39 UTC, pierreprinetti commented on provider_client.go
> +	req, err := http.NewRequestWithContext(ctx, method, url, body)
Look we have a problem a couple lines below. If the Provider client contained a context, then that one will simply override this one. One solution could be to merge the two contexts with something like this: https://github.com/gophercloud/gophercloud/pull/2274/files#diff-552f47512a00afe5fc6850cc9ddc830a6daeca162750e50aab4ed549685e0253R28

2023-10-04 04:36 UTC, pkenchap commented
I see error in the test while running in the devstack - https://github.com/pkenchap/gophercloud/actions/runs/6399950070/job/17376868830#step:3:2273
what need to address here . 

[Call Trace]
./stack.sh:238:die
Error:  ./stack.sh:238 If you wish to run this script anyway run with FORCE=yes
/home/runner/work/gophercloud/gophercloud/devstack/functions-common: line 310: /tmp/devstack-logs/error.log: No such file or directory
Error: Process completed with exit code 1.
##[debug]Finished: run
##[debug]Finishing: Deploy devstack

2023-10-04 15:52 UTC, dulek commented
> I see error in the test while running in the devstack - https://github.com/pkenchap/gophercloud/actions/runs/6399950070/job/17376868830#step:3:2273 what need to address here .
> 
> [Call Trace] ./stack.sh:238:die Error: ./stack.sh:238 If you wish to run this script anyway run with FORCE=yes /home/runner/work/gophercloud/gophercloud/devstack/functions-common: line 310: /tmp/devstack-logs/error.log: No such file or directory Error: Process completed with exit code 1. ##[debug]Finished: run ##[debug]Finishing: Deploy devstack

You got to read the log more carefully, it's saying plainly that focal is no longer supported:
```
+ ./stack.sh:main:233                      :   SUPPORTED_DISTROS='bookworm|bullseye|jammy|rhel8|rhel9|openEuler-22.03'
+ ./stack.sh:main:235                      :   [[ ! focal =~ bookworm|bullseye|jammy|rhel8|rhel9|openEuler-22.03 ]]
+ ./stack.sh:main:236                      :   echo 'WARNING: this script has not been tested on focal'
WARNING: this script has not been tested on focal
+ ./stack.sh:main:237                      :   [[ no != \y\e\s ]]
+ ./stack.sh:main:238                      :   die 238 'If you wish to run this script anyway run with FORCE=yes'
+ functions-common:die:264                 :   local exitcode=0
+ functions-common:die:265                 :   set +o xtrace
```

You can try using `stable/2023.01` branch instead: https://opendev.org/openstack/devstack/src/branch/stable/2023.1/stack.sh#L232.

2023-12-01 05:34 UTC, SasSwart commented
Hey Folks,

I see that the last activity on this PR was about 2 months ago. Is there anything I can do to help this get over the line? We could really use this. I see a few comments still open and that a rebase is needed.

Can I go ahead and make these changes? Would you be interested in continuing this conversation?

2024-02-02 12:17 UTC, pierreprinetti commented
@SasSwart @pkenchap I am adding WithContext methods to ProviderClient and ServiceClient here: https://github.com/gophercloud/gophercloud/pull/2883

This should be a basis for future implementation of context-aware calls in the modules (`servers.CreateWithContext`, `subnets.DeleteWithContext` etc). Please have a look!

2024-02-02 14:16 UTC, pierreprinetti commented
The functionality proposed here has been merged. Please open a new PR if you want to contribute to adding `WithContext` methods to the individual packages.

2024-02-02 14:16 UTC, closed without merging