Add bootable filter to v3 cinder list options
gophercloud/gophercloud pull request #2978
Opened 2024-03-08 11:43 UTC by Wieneo

Fixes #2977

This PR adds the ability to filter volumes by the "bootable" flag, when using Cinder API V3.

2024-03-08 15:24 UTC, mandre requested changes
Thanks for the PR. We want to make this new boolean field a pointer otherwise we're sending `bootable=false` when it's unset.

Could you check that this still works when your openstack is configured without the [bootable resource filter](https://docs.openstack.org/api-ref/block-storage/v3/index.html#resource-filters-resource-filters)? If not, we probably also want to add an omitempty tag to the field so that we're not sending a filter that will confuse OpenStack.

2024-03-11 08:42 UTC, Wieneo commented
@mandre 
You are totally right, I made the bool a pointer.

Unfortunately I cannot test this change with an OS environment, without the bootable flag.
I added the requested "omitempty" flag :)

2024-03-11 10:27 UTC, mandre reviewed
Weirdly enough, @pierreprinetti showed me that the `omitempty` tag seems to [have no effect](https://go.dev/play/p/tsv0yOOowHq). But let's keep it anyway as it shows our intent to drop the field if it's empty.

2024-03-11 10:27 UTC, mandre commented on openstack/blockstorage/v3/volumes/requests.go
> +	// Bootable will filter results based on if they are bootable volumes
Just a small nit
```suggestion
	// Bootable will filter results based on whether they are bootable volumes
```

2024-03-11 10:37 UTC, mandre approved these changes

2024-03-11 15:46 UTC, merged