Add missing contexts to go docs
gophercloud/gophercloud pull request #3011
Opened 2024-03-24 20:57 UTC by mandre

Gophercloud was made context aware in https://github.com/gophercloud/gophercloud/pull/2936, however we forgot to update the go doc comments to match the new function signatures.

This patch was mostly generated with the following command:
```
for f in $(git show https://github.com/gophercloud/gophercloud/commit/1b7c1ceb72b30b5dada9993e8113a67fa95ab419 | grep "+func" | cut -d "(" -f 1 | cut -d " " -f 2 | sort | uniq | tail -n +2); do
        find . -name doc.go -exec sed -i "s/$f(\(\w\?\+[Cc]lient\)/$f(context.TODO(), \1/g" {} \;;
done
```

Then manual edits for List functions that shouldn't have been modified.

2024-03-24 22:52 UTC, pierreprinetti commented
Definitely the most cursed sed invocation I’ve seen so far in 2024 👏

2024-03-25 09:27 UTC, pierreprinetti requested changes

2024-03-25 09:27 UTC, pierreprinetti commented on docs/contributor-tutorial/.template/requests.go
> +func Get(ctx context.Contest, client *gophercloud.ServiceClient, id string) (r GetResult) {
contest typo

2024-03-25 12:01 UTC, mandre commented on docs/contributor-tutorial/.template/requests.go
> +func Get(ctx context.Contest, client *gophercloud.ServiceClient, id string) (r GetResult) {
Oh good catch. Fixed.

2024-03-25 12:03 UTC, pierreprinetti approved these changes

2024-03-25 12:18 UTC, merged